---
language: python
python: '2.7'

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml
  - sudo sh -c 'echo hello > /var/www/repo/manifests/site_default'
  - test "$(curl --silent http://localhost/repo/manifests/site_default)" == 'hello'
  - smbclient --user munki --command 'rm manifests\site_default' //localhost/repo munki
  - ansible-playbook -i tests/inventory tests/test.yml | tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
